spring:
  application:
    name: coursesplatform
  datasource:
    url: jdbc:postgresql://localhost:5432/courses_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  logging:
    file:
      name: logs/app.log
    level:
      root: INFO

jwt:
  secret: "XK5kP9wQ2yLv8aFgR7jHn0sT4xZb6cV1mN3qAeIoBd5tJhMpLfYrU7zWkSdO4iGxE9uCy2vKb1oDl8Q5+3aHnP9wQ2yLv8aFgR7jHn0sT4xZb6cV1mN3qAeIoBd5tJhMpLfYrU7zWkSdO4iGxE9uCy2vKb1oDl8Q5"
  expiration-ms: 86400000  # 24 часа